TigerReports:
  Version: 1.8+ spigot
  Creator: MrTigreroux
  Description: Plugin de gestion de signalements.
  Finished on: 30/06/2016
Config:
  ColorCharacter: '&'
  LineBreakSymbol: "//"
  PermissionRequired: no
  ReportOnline: no
  MaxReports: 100
  MinCharacters: 4
  ReportCooldown: 300
  PunishSeconds: 3600
  MenuSound: ENTITY_ITEM_PICKUP
  ErrorSound: ENTITY_ITEM_BREAK
  ReportSound: ENTITY_BAT_DEATH
  TeleportSound: ENTITY_ENDERMEN_TELEPORT
  StaffSound: ENTITY_ITEM_PICKUP
  DefaultReasons:
    Reason1:
      Name: "Fly"
      Item: Material-Feather
    Reason2:
      Name: "Speed"
      Item: Material-Chainmail_leggings
    Reason3:
      Name: "ForceField"
      Item: Material-Iron_sword
    Reason4:
      Name: "Reach"
      Item: Material-Stick
    Reason5:
      Name: "RapidBowShot"
      Item: Material-Bow
    Reason6:
      Name: "NoKnockback"
      Item: Material-Fishing_rod
    Reason7:
      Name: "Grief"
      Item: Material-TNT
    Reason8:
      Name: "Vol"
      Item: Material-Chest
    Reason9:
      Name: "Insultes"
      Item: Material-Sign