name: TigerReports
version: 3.7
description: Plugin to manage reports / Plugin de gestion de signalements.
author: MrTigreroux
main: fr.mrtigreroux.tigerreports.TigerReports
commands:
  tigerreports:
    description: Informations about TigerReports plugin / Informations sur le plugin TigerReports.
    aliases: [tigerreport]
  report:
    description: Lets report a player / Permet de signaler un joueur.
  reports:
    description: Lets manage reports / Permet de gérer les signalements.
permissions:
  tigerreports.*:
    default: op
    children:
       tigerreports.manage: true
  tigerreports.manage:
    children:
       tigerreports.staff.*: true
  tigerreports.staff.*:
    children:
        tigerreports.staff.advanced: true
        tigerreports.staff.remove: true
        tigerreports.staff.archive: true
        tigerreports.staff.teleport: true
        tigerreports.staff: true
  tigerreports.staff.advanced:
    children:
       tigerreports.staff: true
  tigerreports.staff.remove:
    children:
       tigerreports.staff: true
  tigerreports.staff.archive.auto:
    children:
       tigerreports.staff.archive: true
  tigerreports.staff.archive:
    children:
       tigerreports.staff: true
  tigerreports.staff.teleport:
    children:
       tigerreports.staff: true
  tigerreports.staff:
    children:
       tigerreports.report: true
  tigerreports.report.exempt:
    children:
       tigerreports.report: true