TigerReports:
  Version: 1.7+ spigot
  Author: MrTigreroux
  Description: Management of reports / Gestion de signalements.
Config:
  ColorCharacter: '&'
  # Character used for colors in messages.yml / Caractère utilisé pour les couleurs dans messages.yml
  LineBreakSymbol: "//"
  # Symbol used to separate lines in messages.yml / Symbole utilisé pour séparer les lignes dans messages.yml
  InfoLanguage: French
  # Language used in info messages of the plugin like warnings and /tigerreports help command / Langue utilisée pour les messages d'information comme les avertissements et la commande d'aide /tigerreports
  # Only 2 languages : French and English / Seulement 2 langues : French et English
  PermissionRequired: no
  # Permission needed to use /report command / Permission requise pour utiliser la commande /report
  ReportOnline: no
  # Report only online players / Signaler uniquement des joueurs connectés
  MaxReports: 100
  # Maximum amount of saved reports, others are just displayed in the chat / Nombre maximum de signalements sauvegardés, les autres sont simplement affichés dans le chat
  MinCharacters: 3
  # Minimum amount of characters in the reason of a report / Nombre minimum de caractères pour la raison d'un signalement
  ReportCooldown: 300
  # Cooldown in seconds between each report / Temps en secondes d'attente entre chaque signalement
  ReportedImmunity: 120
  # Time in seconds during the reported player cannot be reported again / Temps en secondes durant lequel un joueur signalé ne peut être à nouveau signalé
  AutoCommands: none
  # List of executed commands after a report, put "none" to don't execute any / Liste des commandes exécutées après chaque signalement, mettre "none" pour aucune
  # Usable tags:    _Server_, _Date_, _Reporter_, _Reported_ and _Reason_
  PunishSeconds: 3600
  # Cooldown inflicted for an abusive report / Temps d'attente infligé pour un signalement abusif
  MessagesHistory: 5
  # Amount of saved messages / Nombre de messages sauvegardés
  CommandsHistory: none
  # - msg
  # - tell
  # List of saved commands in messages history, put "none" to don't save any / Liste des commandes sauvegardées dans l'historique des messages, mettre "none" pour aucune
  Notifications:
    Delay: 2
    # Time in seconds before sending the notification after the connection of the user / Delai en secondes avant d'envoyer la notification après la connexion de l'utilisateur
    Players: true
    # Notify players about the decisions made on their reports / Informer les joueurs des décisions prises sur leurs signalements
    Staff:
      Connection: yes
      MinutesInterval: 0
    # Notifications about reports to process / Notifications à propos des signalements à traiter
    # Connection:    Display at staff connection / Afficher à la connexion d'un membre de l'équipe
    # MinutesInterval:    Display each x minutes, put 0 to disable / Afficher toutes les x minutes, mettre 0 pour désactiver
  OnlyDoneArchives: no
  # Prevent archive of unprocessed reports / Empêcher l'archivage de signalements non traités
  MenuUpdatesInterval: 10
  # Update opened menus each x seconds / Actualiser les menus ouverts toutes les x secondes
  MenuSound: ENTITY_ITEM_PICKUP
  ErrorSound: ENTITY_ITEM_BREAK
  ReportSound: ENTITY_BAT_DEATH
  TeleportSound: ENTITY_ENDERMEN_TELEPORT
  StaffSound: ENTITY_ITEM_PICKUP
  # Bukkit sounds used on specific actions / Sons bukkit utilisés pour certaines actions
  # Put 'none' to disable the sound / Mettre 'none' pour désactiver le son
  CustomReasons: yes
  # Allow custom reasons / Autoriser les raisons personnalisées
  DefaultReasons:
    Reason1:
      Name: "Fly"
      Lore: "&7Le joueur se d\xe9place dans//&7les airs."
      Item: Material-Feather
      PunishCommands:
      - "ban _Player_ 7d Fly"
    Reason2:
      Name: "Speed"
      Lore: "&7Le joueur se d\xe9place anormalement//&7vite."
      Item: Material-Chainmail_leggings
      PunishCommands:
      - "ban _Player_ 7d Speed"
    Reason3:
      Name: "ForceField"
      Lore: "&7Le joueur tape les joueurs/entit\xe9s//&7proches de lui de fa\u00E7on suspecte."
      Item: Material-Iron_sword
      PunishCommands:
      - "ban _Player_ 14d ForceField"
    Reason4:
      Name: "Reach"
      Lore: "&7Le joueur tape de tr\u00E8s loin//&7les joueurs/entit\xe9s."
      Item: Material-Stick
      PunishCommands:
      - "ban _Player_ 7d Reach"
    Reason5:
      Name: "RapidBowShot"
      Lore: "&7Le joueur tire des fl\u00E8ches//&7tr\u00E8s vite."
      Item: Material-Bow
      PunishCommands:
      - "ban _Player_ 7d RapidBowShot"
    Reason6:
      Name: "NoKnockback"
      Lore: "&7Le joueur ne recule pas//&7lorsqu'il est frapp\xe9."
      Item: Material-Fishing_rod
      PunishCommands:
      - "ban _Player_ 7d NoKnockback"
    Reason7:
      Name: "Grief"
      Lore: "&7Le joueur a d\xe9grad\xe9 une de//&7mes constructions."
      Item: Material-TNT
      PunishCommands:
      - "ban _Player_ 2d Grief"
    Reason8:
      Name: "Vol"
      Lore: "&7Le joueur m'a vol\xe9 des ressources."
      Item: Material-Chest
      PunishCommands:
      - "ban _Player_ 1d Vol"
    Reason9:
      Name: "Insultes"
      Lore: "&7Le joueur est irrespectueux."
      Item: Material-Sign
      PunishCommands:
      - "mute _Player_ 2h Insultes"
  # Default reasons displayed in a menu / Raisons par défaut affichées dans un menu
  # Name:    Reason of the report / Raison du signalement
  # Lore:    Description of the report / Description du signalement
  # Item:    Material-<item_type>(:damage) or/ou Skull-<pseudo>
  #   Examples:    Material-Stone = Stone / Pierre    Material-Wool:2 = Magenta Wool / Laine magenta    Skull-MrTigreroux = Skull of player MrTigreroux / Tête du joueur MrTigreroux
  # PunishCommandes:    List of commands to execute when punishing / Liste des commandes à exécuter lors d'une sanction.
  Punishments:
    DefaultReasons: yes
    # Use defaults reasons as punishments / Utiliser les raisons par défaut comme des sanctions.
    # "Punishments:" property must be added below each default reason / La propriété "Punishments:" doit être ajoutée en-dessous de chaque raison par défaut.
    Punishment1:
      Name: "R\xe9cidive de triche"
      Lore: "&7Le joueur r\xe9utilise un hack."
      Item: Material-TNT
      PunishCommands:
      - "ban _Player_ 1m R\xe9cidive de triche"
    Punishment2:
      Name: "Harc\u00E8lement"
      Lore: "&7Le joueur harc\u00E8le les autres."
      Item: Material-Pumpkin
      PunishCommands:
      - "ban _Player_ 7d Harc\u00E8lement"
  # Punishments available after processing a report as True / Sanctions disponibles après avoir traité un signalement comme vrai.
  # Name:    Name of the punsihment / Nom de la sanction
  # Lore:    Description of the punishment / Description de la sanction
  # Item:    Material-<item_type>(:damage) or/ou Skull-<pseudo>
  #   Examples:    Material-Stone = Stone / Pierre    Material-Wool:2 = Magenta Wool / Laine magenta    Skull-MrTigreroux = Skull of player MrTigreroux / Tête du joueur MrTigreroux
  # PunishCommandes:    List of commands to execute when punishing / Liste des commandes à exécuter lors d'une sanction.
BungeeCord:
  Enabled: yes
  # Interact with the BungeeCord network / Intéragir avec le réseau BungeeCord
  Servers:
    server1: "Serveur 1"
  # Custom display name of servers / Nom personnalisé des serveurs
MySQL:
  Host: ""
  Port: 0
  Database: ""
  Username: ""
  Password: ""
# Login IDs of connection to a MySQL database / Identifiants de connexion à une base de données MySQL